### PR TITLE
Leak ieq

### PR DESCRIPTION
**Pull request by sohailreddy**
Update contains mods to:
1) treat leakage using an inequality constraint (called leak-ieq)
2) include capability for both Neumann series and Jacobi solver
3) doc updates for the new mods
4) CI test cases for leak-ieq and Jacobi

### CODE REVIEW

**Comment by andersp** [comment]
@sohailrreddy Can you fix the cnot3 test case? Right now there is a problem in traceobjgrad(), see the details under Testing/test

**Comment by andersp** [comment]
@sohailrreddy For consistency it would be good to also build the docs using v1.7 of Julia

**Comment by sohailreddy** [comment]
> @sohailrreddy For consistency it would be good to also build the docs using v1.7 of Julia

@andersp  It's now updated to run the CI tests and doc-build with both v1.6 and v1.7 on both macOS and ubuntu

**Comment by andersp** [comment]
@sohailrreddy There are problems running some of the original cases in the examples folder. Probably related to these lines in cnot1-setup.jl:
include("../src/Juqbox.jl")
using .Juqbox # quantum control module

**Comment by andersp** [comment]
@sohailrreddy The derivative checker seems to be enabled for all setup files in the examples folder. Please revert this setting (ok to comment out those lines)

**Comment by fortinog** [comment]
I would also agree that it might be best to not enable the derivative checker by default in the `ipopt_interface.jl` file. For much larger problems like the `cnot3-setup.jl` this takes quite a long time to perform.

**Comment by andersp** [comment]
@sohailrreddy you should increment the version number to make it more obvious that anything has changed

**Comment by sohailreddy** [comment]
> @sohailrreddy you should increment the version number to make it more obvious that anything has changed

done, it has been updated to v0.2.0

**Comment by sohailreddy** [comment]
> @sohailrreddy The derivative checker seems to be enabled for all setup files in the examples folder. Please revert this setting (ok to comment out those lines)

> I would also agree that it might be best to not enable the derivative checker by default in the `ipopt_interface.jl` file. For much larger problems like the `cnot3-setup.jl` this takes quite a long time to perform.

Derivative checker has now been turned off by default.

**Comment by sohailreddy** [comment]
> @sohailrreddy There are problems running some of the original cases in the examples folder. Probably related to these lines in cnot1-setup.jl:
> include("../src/Juqbox.jl")
> using .Juqbox # quantum control module

The error occurred because Juqbox.jl packages need to be installed through the package manager. This has been fixed in the latest push

**Comment by andersp** [comment]
@sohailrreddy I'm looking at your l_solver struct and how it is tested in the cnot2-jacobi-setup case. I noticed that the Jacobi solver is slower than the Neumann solver, even after increasing the tolerance to 1e-10. This is probably because you don't provide an `rwork` array with the correct non-zero dimension, which forces the 'xold' array to be allocated on every call to your Jacobi solver. It would be better to require the nvars and ndim arguments in the constructor. And it would be good if you could setup the cnot2 cases (Neumann & Jacobi) with the same tolerances, to make the comparison easier.

**Comment by sohailreddy** [comment]
@andersp, There is an rwork array within the `lsolver_object` struct that is created and correctly dimensioned when the `Working_Arrays ` struct is created. `allocate_linear_solver_arrays` function will then recreate the closure with the correctly dimensioned `lsolver.rwork` to be reused for all subsequent calls to the linear solver.

https://github.com/LLNL/Juqbox.jl/blob/21e3cad0b2dae868e20267679e0d42e2cd0d1b04/src/linear_solvers.jl#L64

Jacobi will be slower than Neumann when ran for same # of iterations since the prior requires additional operations to check the residuals. From initial testing, for a tolerance of 1e-10, Jacobi still needed 3-4 iterations in which case Neumann (with the default 3 iters) will be faster.

**Comment by andersp** [comment]
But when you call it in your example, cnot2-jacobi-setup.jl, you don't provide nvars or ndims, which leaves them at their default values (zero)

**Comment by andersp** [comment]
@sohailrreddy Also, it would be good to print out the type of time-integration method, and their parameters, during initialization.

**Comment by sohailreddy** [comment]
Yes because we want the objects to deduce the size instead of having the user to compute and feed into the constructor. Instead, the function resizes the arrays when the size is known in the (i.e. `Working_Arrays` constructor)

The function
https://github.com/LLNL/Juqbox.jl/blob/21e3cad0b2dae868e20267679e0d42e2cd0d1b04/src/evalobjgrad.jl#L362
then resizes the linear solvers and recreates the closure with the newly resized work arrays

https://github.com/LLNL/Juqbox.jl/blob/21e3cad0b2dae868e20267679e0d42e2cd0d1b04/src/linear_solvers.jl#L59

https://github.com/LLNL/Juqbox.jl/blob/21e3cad0b2dae868e20267679e0d42e2cd0d1b04/src/linear_solvers.jl#L64

**Comment by andersp** [comment]
So why do you have nvars and ndims as optional args in the constructor?
function lsolver_object(;nvar::Int64 = 0, ndim::Int64 = 0, tol::Float64 = 1e-10, 
                            iter::Int64 = 3, solver::Int64 = NEUMANN_SOLVER)

**Comment by sohailreddy** [comment]
It's multi-purposed. I left them there in case we want to extend the linear solvers in the future or if we want to solve other linear systems without having to go through the `Working_Arrays` routines. 

It's also helpful to hold the object's info within the object member variables if we ever need to query it (instead of using size(), length() on its member arrays to get the same information).

**Comment by andersp** [comment]
@sohailrreddy The design needs some improvements because the Jacobi solver wouldn't work if you only called the lsolver_object constructor. You could avoid all these troubles if you instead required the nvars and ndims arguments and added another option to the objparams() constructor and created the lsolver_object inside of it. Then you don't need the allocate_linear_solvers function.

**Comment by andersp** [comment]
@sohailrreddy There is a better way to implement Jacobi that only needs one temporary vector (T). I will show you this PM.

**Pull request merged**
